// GENERATED by dev/tools/build_bold.py from dev/docs/mental.md: don't hand-edit.
// The bolded effects of each Mode / ability that contain a number (they scale with Wonder Power).
export const BOLD = {
 "Wonder Power": [
  "1d8 damage",
  "3d8 damage"
 ],
 "Ranged": [
  "maximum range of 100ft"
 ],
 "Neutral": [
  "1 Alignment:",
  "2 Alignment:",
  "3 Alignment:",
  "4 Alignment:"
 ],
 "Bloom": [
  "20 temp HP"
 ],
 "Verdant Soul": [
  "10 temp HP"
 ],
 "Flourish": [
  "+1 die size"
 ],
 "Renewal": [
  "4 health"
 ],
 "Wither": [
  "2d10 health"
 ],
 "Mortal Coil": [
  "1d8"
 ],
 "Waste": [
  "die size by 2"
 ],
 "Execute": [
  "1d12"
 ],
 "Decree": [
  "plus or minus 1"
 ],
 "Balance": [
  "add 1",
  "remove 1"
 ],
 "Mandate": [
  "plus or minus 1",
  "plus or minus 10"
 ],
 "Verdict": [
  "add/subtract 5"
 ],
 "Fracture": [
  "increased or decreased by 2"
 ],
 "Larceny": [
  "increased or decreased by 1"
 ],
 "Entropy": [
  "increased or decreased by 3"
 ],
 "Herald": [
  "10d8 Force"
 ],
 "Gust": [
  "5d8 Force"
 ],
 "Momentum": [
  "5d8 Force"
 ],
 "Redirect": [
  "20 less damage",
  "reduces damage by 10"
 ],
 "Ascend": [
  "60 Lift"
 ],
 "Sink": [
  "2 or higher"
 ],
 "Weight": [
  "15 Slow stacks"
 ],
 "Vice": [
  "1d12 physical"
 ],
 "Burden": [
  "2 or higher"
 ],
 "Entomb": [
  "3 or higher",
  "3d10 physical damage"
 ],
 "Fabricate": [
  "Body of up to 15"
 ],
 "Corrode": [
  "2d6 acid damage"
 ],
 "Immolate": [
  "2d10 heat damage"
 ],
 "Irradiate": [
  "2d8 radiation damage",
  "1 additional damage",
  "healing effects by 1"
 ],
 "Freeze": [
  "2d8 cold damage"
 ],
 "Pacify": [
  "-2 die size",
  "reduced by 1d8",
  "+1 die size",
  "1d8"
 ],
 "Dampen": [
  "reduce that damage by 1d10"
 ],
 "Absolution": [
  "5"
 ],
 "Guard": [
  "15 of that damage"
 ],
 "Provoke": [
  "2 die size"
 ],
 "Empower": [
  "increase that damage by 1d10"
 ],
 "Warmonger": [
  "1d12 of the attack’s damage type"
 ],
 "Warzone": [
  "1d8 of that attack’s damage type"
 ],
 "Bloodbond": [
  "10 of the damage they dealt"
 ],
 "Crescendo": [
  "1d10 Physical damage"
 ],
 "Adaptive Skin": [
  "reducing all damage they take by 1",
  "grants 1 damage reduction",
  "grants 1 more damage reduction"
 ],
 "Second Wind": [
  "restores 5 energy"
 ],
 "Exact": [
  "1d10 Physical damage",
  "5 Pierce"
 ],
 "Ego": [
  "5 energy"
 ],
 "Hone": [
  "attack roll results by 1",
  "1"
 ],
 "Masterstroke": [
  "1d8 damage of your choice",
  "1d8"
 ]
};
