#!/usr/bin/env python3
"""Pull the bolded numbers out of the Mental doc (dev/docs/mental.md): every bolded effect of a Wonder scales with its Power.
Writes module/mental-bold.mjs: { "<Mode or ability name>": ["bolded text with a number", ...] }."""
import re, json, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
text = (root / "dev/docs/mental.md").read_text()
skip = re.compile(r"grade of|\bAP\b|\bRP\b|\bft\b|Skill Trees|^Cost|^Tier", re.I)
out, cur = {}, None
for ln in text.split("\n"):
    m = re.match(r"^\s*(?:- )?\*\*([A-Z][A-Za-z' ]+?):\*+", ln)
    if m: cur = m.group(1).strip()
    if not cur or ln.startswith("#"): continue
    for span in re.findall(r"\*\*(.+?)\*\*", ln):
        s = span.replace("\\+", "+").replace("\\-", "-").replace("\\", "").strip(" ,.")
        if re.search(r"\d", s) and not skip.search(s) and len(s) < 80:
            out.setdefault(cur, [])
            if s not in out[cur]: out[cur].append(s)
body = "// GENERATED by dev/tools/build_bold.py from dev/docs/mental.md: don't hand-edit.\n// The bolded effects of each Mode / ability that contain a number (they scale with Wonder Power).\nexport const BOLD = " + json.dumps(out, indent=1, ensure_ascii=False) + ";\n"
(root / "module/mental-bold.mjs").write_text(body)
print(len(out), "entries")
